### ISSUE TITLE
possible fix for no audio

### ISSUE THREAD

**Issue by Frisk4973** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#19]
try adding a button that when clicked triggers the start audio and see if that works, because of the usergesture policy preventing the audio from playing

**Comment by burnedpopcorn** [comment]
no, I'm pretty sure it's an FMOD problem, as FMOD is not supported on GX.GAMES, and locating files in a Web Browser is different from a Windows environment, so even if it can initialize, it probably can't and won't locate the .bank files anyways.

Best solution is probably to extract the .wav files from the .bank files, and manually import them and replace every call to FMOD to a call to the old sound code that is left over

Unfortunately, I am unable to make or develop any new updates at the moment because of a certain relative's anger issues, so I currently have no means of updating this project further, although I continue work as soon as possible
